export const initialState = {
  tab: "editor",
  imageUrl: null,
  imageId: null,
  imageName: null,
  uploadLoading: false,
  uploadError: null,
  hotspots: [],
  selectedHotspotId: null,
  finalizeLoading: false,
  finalizeError: null,
  lastFinalizedLogId: null,
  lastFinalizedHash: null,
  lastFinalizedImageFileHash: null,
  lastFinalizedCreatedAt: null,
  verifyLoading: false,
  verifyError: null,
  verifyResult: null,
};