export const initialState = {
  tab: "editor" as "editor" | "verify",
  imageUrl: null as string | null,
  imageId: null as string | null,
  imageName: null as string | null,
  uploadLoading: false,
  uploadError: null as string | null,
  hotspots: [] as any[],
  selectedHotspotId: null as string | null,
  finalizeLoading: false,
  finalizeError: null as string | null,
  lastFinalizedLogId: null as string | null,
  lastFinalizedHash: null as string | null,
  lastFinalizedImageFileHash: null as string | null,
  lastFinalizedCreatedAt: null as string | null,
  verifyLoading: false,
  verifyError: null as string | null,
  verifyResult: null as any | null,
};