import React, { useState } from "react";
import { base44 } from "@/api/base44Client";
import { promptLLM } from "@/components/utils/llmClient";
import { FileText, Download, Loader2, Shield, CheckCircle } from "lucide-react";

export default function AuditGenerator() {
  const [auditType, setAuditType] = useState("security");
  const [scope, setScope] = useState("");
  const [generating, setGenerating] = useState(false);
  const [audit, setAudit] = useState(null);

  const generateAudit = async () => {
    if (!scope.trim()) return;

    setGenerating(true);
    setAudit(null);

    try {
      const user = await base44.auth.me().catch(() => ({ email: "unknown" }));
      
      let prompt = "";
      
      if (auditType === "security") {
        prompt = `Generate a comprehensive security audit report for: ${scope}

Include:
1. Executive Summary
2. Scope & Methodology
3. Security Assessment
   - Access Controls
   - Data Protection
   - Network Security
   - Application Security
4. Vulnerability Analysis
5. Compliance Check (GDPR, SOC2, ISO27001)
6. Risk Assessment Matrix
7. Recommendations
8. Action Plan
9. Master Covenant Compliance Review

Format as a professional audit document.`;
      } else if (auditType === "compliance") {
        prompt = `Generate a compliance audit report for: ${scope}

Include:
1. Regulatory Framework Review
2. Compliance Status
3. Gap Analysis
4. Policy Review
5. Documentation Assessment
6. Training & Awareness
7. Incident Response Readiness
8. Third-Party Risk Management
9. Remediation Roadmap

Focus on GDPR, CCPA, SOC2, ISO27001, and Master Covenant principles.`;
      } else {
        prompt = `Generate a system integrity audit for: ${scope}

Include:
1. System Architecture Review
2. Code Quality Assessment
3. Performance Analysis
4. Scalability Evaluation
5. Reliability Metrics
6. Maintenance Status
7. Technical Debt Assessment
8. Upgrade Roadmap
9. Best Practices Compliance

Provide actionable insights and recommendations.`;
      }

      const response = await promptLLM(prompt);

      const auditData = {
        id: crypto.randomUUID(),
        type: auditType,
        scope,
        generatedBy: user.email,
        timestamp: new Date().toISOString(),
        content: response,
        metadata: {
          promptVersion: "v2.0",
          model: "gemini-1.5-pro",
          covenantCompliant: true
        }
      };

      setAudit(auditData);

      // Log audit generation
      await base44.entities.SystemAuditLog.create({
        event_type: "GLYPHBOT_AUDIT_GENERATED",
        description: `${auditType} audit generated`,
        actor_email: user.email,
        resource_id: "glyphbot",
        metadata: { auditType, scope, auditId: auditData.id },
        status: "success"
      }).catch(console.error);

    } catch (error) {
      console.error("Audit generation error:", error);
      setAudit({
        error: "Failed to generate audit. Please try again.",
        timestamp: new Date().toISOString()
      });
    } finally {
      setGenerating(false);
    }
  };

  const downloadAudit = () => {
    if (!audit || audit.error) return;

    const content = `
GLYPHLOCK SECURITY AUDIT REPORT
================================

Audit ID: ${audit.id}
Type: ${audit.type.toUpperCase()}
Generated: ${new Date(audit.timestamp).toLocaleString()}
Generated By: ${audit.generatedBy}
Scope: ${audit.scope}

${audit.content}

---
Report certified by GlyphBot AI Security System
Master Covenant Compliant
`;

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `glyphlock-audit-${audit.type}-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="h-full flex flex-col p-6">
      <div className="mb-6">
        <h2 className="text-2xl font-bold text-white mb-2">Audit Generator</h2>
        <p className="text-gray-400">Generate comprehensive security and compliance audit reports</p>
      </div>

      <div className="flex-1 overflow-y-auto space-y-4">
        <div className="bg-green-500/10 border border-green-500 rounded-lg p-4 flex items-start gap-3">
          <CheckCircle className="w-5 h-5 text-green-400 flex-shrink-0 mt-0.5" />
          <div className="text-sm text-green-400">
            <p className="font-semibold mb-1">Master Covenant Compliant</p>
            <p>All audits follow GlyphLock's Master Covenant security principles and industry standards.</p>
          </div>
        </div>

        <div className="space-y-3">
          <label className="block text-sm font-medium text-gray-300">
            Audit Type
          </label>
          <div className="grid grid-cols-3 gap-2">
            {["security", "compliance", "system"].map(type => (
              <button
                key={type}
                onClick={() => setAuditType(type)}
                className={`px-4 py-2 rounded-lg border font-medium capitalize transition-all ${
                  auditType === type
                    ? "border-cyan-400 bg-cyan-400/10 text-cyan-400"
                    : "border-gray-700 bg-gray-900 text-gray-400 hover:border-gray-600"
                }`}
              >
                {type}
              </button>
            ))}
          </div>
        </div>

        <div className="space-y-3">
          <label className="block text-sm font-medium text-gray-300">
            Audit Scope
          </label>
          <textarea
            value={scope}
            onChange={(e) => setScope(e.target.value)}
            placeholder="Describe what should be audited (e.g., 'Web application authentication system', 'GDPR compliance for customer data', 'Payment processing infrastructure')..."
            rows={6}
            className="w-full p-4 bg-gray-900 border border-gray-700 rounded-lg text-white resize-none focus:outline-none focus:border-cyan-400"
          />
        </div>

        <button
          onClick={generateAudit}
          disabled={generating || !scope.trim()}
          className="w-full flex items-center justify-center gap-2 px-4 py-3 rounded-lg bg-gradient-to-r from-cyan-600 to-blue-600 text-white font-semibold disabled:opacity-50 hover:from-cyan-500 hover:to-blue-500 transition-all"
        >
          {generating ? (
            <>
              <Loader2 className="w-5 h-5 animate-spin" />
              Generating Audit...
            </>
          ) : (
            <>
              <FileText className="w-5 h-5" />
              Generate Audit Report
            </>
          )}
        </button>

        {audit && (
          <div className="bg-gray-900 rounded-xl p-6 border border-gray-800">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-2">
                <Shield className="w-5 h-5 text-cyan-400" />
                <h3 className="text-lg font-bold text-white">Audit Report</h3>
              </div>
              
              {!audit.error && (
                <button
                  onClick={downloadAudit}
                  className="flex items-center gap-2 px-4 py-2 rounded-lg bg-green-600 text-white hover:bg-green-500 transition-colors"
                >
                  <Download className="w-4 h-4" />
                  Download
                </button>
              )}
            </div>

            {audit.error ? (
              <div className="p-4 bg-red-500/10 border border-red-500 rounded-lg">
                <p className="text-red-500">{audit.error}</p>
              </div>
            ) : (
              <div className="space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div className="p-3 bg-gray-800 rounded-lg">
                    <p className="text-sm text-gray-400 mb-1">Audit ID</p>
                    <p className="text-xs text-white font-mono">{audit.id}</p>
                  </div>
                  <div className="p-3 bg-gray-800 rounded-lg">
                    <p className="text-sm text-gray-400 mb-1">Type</p>
                    <p className="text-white capitalize">{audit.type}</p>
                  </div>
                  <div className="p-3 bg-gray-800 rounded-lg">
                    <p className="text-sm text-gray-400 mb-1">Generated By</p>
                    <p className="text-white text-sm">{audit.generatedBy}</p>
                  </div>
                  <div className="p-3 bg-gray-800 rounded-lg">
                    <p className="text-sm text-gray-400 mb-1">Timestamp</p>
                    <p className="text-white text-sm">{new Date(audit.timestamp).toLocaleString()}</p>
                  </div>
                </div>

                <div className="p-4 bg-gray-800 rounded-lg">
                  <p className="text-sm text-gray-400 mb-3">Audit Content</p>
                  <div className="max-h-96 overflow-y-auto">
                    <pre className="text-sm text-gray-300 whitespace-pre-wrap">
                      {audit.content}
                    </pre>
                  </div>
                </div>

                <div className="flex items-center gap-2 p-3 bg-green-500/10 border border-green-500 rounded-lg">
                  <CheckCircle className="w-4 h-4 text-green-400" />
                  <p className="text-sm text-green-400">Master Covenant Compliant</p>
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}