import React from 'react';
import { useQuery } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Loader2, FileText, CheckCircle, XCircle, Shield, Download } from 'lucide-react';
import { jsPDF } from 'jspdf'; // Assuming installed or available, if not I'll just simulate print

export default function ComplianceReport() {
  const { data: report, isLoading, error } = useQuery({
    queryKey: ['complianceReport'],
    queryFn: () => base44.functions.invoke('reports/generateCompliance').then(r => r.data)
  });

  const downloadPDF = () => {
    // Simple print implementation for now as jsPDF might need specific config
    window.print();
  };

  if (isLoading) return <div className="flex justify-center p-20"><Loader2 className="w-10 h-10 animate-spin text-cyan-400" /></div>;
  if (error) return <div className="p-10 text-red-400">Error loading report: {error.message}</div>;

  return (
    <div className="min-h-screen bg-white text-slate-900 p-8 print:p-0">
      <div className="max-w-4xl mx-auto">
        <div className="flex justify-between items-start mb-8 print:hidden">
          <div>
             <h1 className="text-3xl font-bold text-slate-900">Compliance & Security Report</h1>
             <p className="text-slate-500">NIST 800-53 / GenAI Challenge Validation</p>
          </div>
          <Button onClick={downloadPDF} className="bg-slate-900 text-white">
            <Download className="w-4 h-4 mr-2" />
            Export / Print
          </Button>
        </div>

        {/* Report Header (Visible in Print) */}
        <div className="border-b-2 border-slate-900 pb-6 mb-8">
            <div className="flex justify-between items-center mb-4">
                <div className="flex items-center gap-2">
                    <Shield className="w-8 h-8 text-blue-600" />
                    <span className="text-2xl font-bold">GlyphLock Security</span>
                </div>
                <div className="text-right">
                    <p className="text-sm text-slate-500">Report ID: {crypto.randomUUID().substring(0,8)}</p>
                    <p className="text-sm text-slate-500">{new Date(report.generatedAt).toLocaleString()}</p>
                </div>
            </div>
            <div className="flex items-center gap-4">
                <Badge className={report.complianceStatus === 'COMPLIANT' ? "bg-green-100 text-green-700 hover:bg-green-100" : "bg-red-100 text-red-700"}>
                    {report.complianceStatus}
                </Badge>
                <span className="text-sm font-mono text-slate-500">Generated by: {report.generatedBy}</span>
            </div>
        </div>

        <div className="space-y-8">
            {/* Section 1: Trust Anchors */}
            <section>
                <h2 className="text-xl font-bold mb-4 flex items-center gap-2">
                    <CheckCircle className="w-5 h-5 text-blue-600" /> 1. Cryptographic Trust Anchors
                </h2>
                <Card className="border-slate-200 shadow-sm">
                    <CardContent className="p-6">
                        <div className="grid grid-cols-2 gap-4 mb-4">
                            <div>
                                <p className="text-sm text-slate-500">Key Status</p>
                                <p className="font-semibold">{report.sections.trustAnchors.status}</p>
                            </div>
                            <div>
                                <p className="text-sm text-slate-500">Active Keys</p>
                                <p className="font-semibold">{report.sections.trustAnchors.activeKeysCount}</p>
                            </div>
                        </div>
                        <table className="w-full text-sm text-left">
                            <thead className="bg-slate-50">
                                <tr>
                                    <th className="p-2">Key ID</th>
                                    <th className="p-2">Type</th>
                                    <th className="p-2">Created</th>
                                </tr>
                            </thead>
                            <tbody>
                                {report.sections.trustAnchors.keys.map(k => (
                                    <tr key={k.kid} className="border-t border-slate-100">
                                        <td className="p-2 font-mono text-xs">{k.kid}</td>
                                        <td className="p-2">{k.keyType}</td>
                                        <td className="p-2">{new Date(k.created).toLocaleDateString()}</td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </CardContent>
                </Card>
            </section>

            {/* Section 2: AI Governance */}
            <section>
                <h2 className="text-xl font-bold mb-4 flex items-center gap-2">
                    <CheckCircle className="w-5 h-5 text-blue-600" /> 2. AI Governance & Accountability
                </h2>
                <Card className="border-slate-200 shadow-sm">
                    <CardContent className="p-6">
                        <p className="mb-4 text-sm text-slate-600">
                            Recent interactions with GlyphBot subject to NIST 800-53 controls and audit logging.
                        </p>
                        <table className="w-full text-sm text-left">
                            <thead className="bg-slate-50">
                                <tr>
                                    <th className="p-2">Timestamp</th>
                                    <th className="p-2">Mode</th>
                                    <th className="p-2">Compliance Check</th>
                                </tr>
                            </thead>
                            <tbody>
                                {report.sections.aiGovernance.recentAudits.map((a, i) => (
                                    <tr key={i} className="border-t border-slate-100">
                                        <td className="p-2">{new Date(a.timestamp).toLocaleString()}</td>
                                        <td className="p-2 capitalize">{a.mode}</td>
                                        <td className="p-2">
                                            <Badge variant="outline" className="text-green-600 border-green-200">
                                                {a.complianceCheck}
                                            </Badge>
                                        </td>
                                    </tr>
                                ))}
                                {report.sections.aiGovernance.recentAudits.length === 0 && (
                                    <tr><td colSpan="3" className="p-4 text-center text-slate-400">No recent AI interactions audited.</td></tr>
                                )}
                            </tbody>
                        </table>
                    </CardContent>
                </Card>
            </section>

             {/* Section 3: NIST Controls Mapping */}
             <section>
                <h2 className="text-xl font-bold mb-4 flex items-center gap-2">
                    <CheckCircle className="w-5 h-5 text-blue-600" /> 3. NIST Control Implementation
                </h2>
                <Card className="border-slate-200 shadow-sm">
                    <CardContent className="p-6">
                        <ul className="space-y-3">
                            {Object.entries(report.nistControls).map(([control, desc]) => (
                                <li key={control} className="flex gap-4">
                                    <span className="font-mono font-bold text-slate-700 w-16 shrink-0">{control}</span>
                                    <span className="text-slate-600 text-sm">{desc}</span>
                                </li>
                            ))}
                        </ul>
                    </CardContent>
                </Card>
            </section>
        </div>
        
        <div className="mt-12 pt-8 border-t border-slate-200 text-center text-xs text-slate-400">
            <p>GlyphLock System Generated Report • Confidential • Internal Use Only</p>
        </div>
      </div>
    </div>
  );
}